/** All demo records use ids starting with this prefix so clearDemo can remove them safely. */
export const DEMO_ID_PREFIX = 'demo-'

const now = Date.now()
export const daysAgo = (d: number) => new Date(now - d * 86400000)
export const daysFromNow = (d: number) =>
  new Date(now + d * 86400000).toISOString().slice(0, 10)

export const DEMO_TASKS = [
  {
    id: 'demo-task-1',
    areaId: 'area-strategy',
    title: 'Finalize FY26 institutional OKRs',
    description: 'Align department heads on top 5 institutional objectives and cascade KPIs.',
    status: 'in_progress',
    priority: 'critical',
    dueDate: daysFromNow(3),
  },
  {
    id: 'demo-task-2',
    areaId: 'area-strategy',
    title: 'Board presentation deck draft',
    description: 'Prepare strategy narrative and progress slides for the quarterly board meet.',
    status: 'todo',
    priority: 'high',
    dueDate: daysFromNow(10),
  },
  {
    id: 'demo-task-3',
    areaId: 'area-qa',
    title: 'NAAC SSR evidence compilation',
    description: 'Collect Criterion 1–7 evidence folders from all departments.',
    status: 'blocked',
    priority: 'critical',
    dueDate: daysFromNow(-2),
  },
  {
    id: 'demo-task-4',
    areaId: 'area-qa',
    title: 'Internal academic audit Cycle 2',
    description: 'Schedule and complete internal audit for Engineering & Management.',
    status: 'in_progress',
    priority: 'high',
    dueDate: daysFromNow(7),
  },
  {
    id: 'demo-task-5',
    areaId: 'area-recruitment',
    title: 'CSE faculty shortlisting',
    description: 'Screen 48 applications for Assistant Professor – CSE positions.',
    status: 'in_progress',
    priority: 'high',
    dueDate: daysFromNow(4),
  },
  {
    id: 'demo-task-6',
    areaId: 'area-recruitment',
    title: 'Lab technician interview panel',
    description: 'Constitute interview panel and share calendars for next week.',
    status: 'todo',
    priority: 'medium',
    dueDate: daysFromNow(8),
  },
  {
    id: 'demo-task-7',
    areaId: 'area-operational',
    title: 'Hostel mess vendor review',
    description: 'Review hygiene scores and renegotiate SLAs with current vendor.',
    status: 'todo',
    priority: 'medium',
    dueDate: daysFromNow(14),
  },
  {
    id: 'demo-task-8',
    areaId: 'area-operational',
    title: 'ERP downtime window communication',
    description: 'Notify all stakeholders about Saturday maintenance window.',
    status: 'done',
    priority: 'low',
    dueDate: daysFromNow(-1),
  },
  {
    id: 'demo-task-9',
    areaId: 'area-special',
    title: 'Innovation lab soft launch',
    description: 'Coordinate soft launch event with 3 industry mentors and student clubs.',
    status: 'in_progress',
    priority: 'high',
    dueDate: daysFromNow(12),
  },
  {
    id: 'demo-task-10',
    areaId: 'area-admissions',
    title: 'Counseling helpline staffing plan',
    description: 'Ensure 24×7 helpline coverage for peak counseling week.',
    status: 'blocked',
    priority: 'critical',
    dueDate: daysFromNow(-1),
  },
  {
    id: 'demo-task-11',
    areaId: 'area-admissions',
    title: 'School outreach roadshow – Phase 1',
    description: 'Visit 12 feeder schools across Jammu region with brochure kits.',
    status: 'in_progress',
    priority: 'high',
    dueDate: daysFromNow(5),
  },
  {
    id: 'demo-task-12',
    areaId: 'area-admissions',
    title: 'Seat matrix freeze for B.Tech',
    description: 'Lock branch-wise seat matrix before counseling portal opens.',
    status: 'done',
    priority: 'critical',
    dueDate: daysFromNow(-5),
  },
]

export const DEMO_KPIS = [
  {
    id: 'demo-kpi-1',
    areaId: 'area-strategy',
    name: 'OKR Completion',
    value: 68,
    target: 85,
    unit: '%',
    trend: 4.2,
    period: 'FY26 Q1',
  },
  {
    id: 'demo-kpi-2',
    areaId: 'area-qa',
    name: 'Audit Closure Rate',
    value: 72,
    target: 90,
    unit: '%',
    trend: -2.1,
    period: 'This quarter',
  },
  {
    id: 'demo-kpi-3',
    areaId: 'area-recruitment',
    name: 'Open Positions Filled',
    value: 12,
    target: 18,
    unit: 'roles',
    trend: 2,
    period: 'This quarter',
  },
  {
    id: 'demo-kpi-4',
    areaId: 'area-operational',
    name: 'SLA Compliance',
    value: 91,
    target: 95,
    unit: '%',
    trend: 1.4,
    period: 'Monthly',
  },
  {
    id: 'demo-kpi-5',
    areaId: 'area-special',
    name: 'Pilot Milestones Hit',
    value: 5,
    target: 8,
    unit: 'milestones',
    trend: 1,
    period: 'This quarter',
  },
  {
    id: 'demo-kpi-6',
    areaId: 'area-admissions',
    name: 'Applications Received',
    value: 1840,
    target: 2500,
    unit: 'apps',
    trend: 12.5,
    period: 'Admission cycle',
  },
  {
    id: 'demo-kpi-7',
    areaId: 'area-admissions',
    name: 'Counseling Conversion',
    value: 38,
    target: 45,
    unit: '%',
    trend: 2.8,
    period: 'This month',
  },
  {
    id: 'demo-kpi-8',
    areaId: 'area-strategy',
    name: 'Strategic Projects On Track',
    value: 7,
    target: 10,
    unit: 'projects',
    trend: 1,
    period: 'This quarter',
  },
]

export const DEMO_ACTIVITY = [
  {
    id: 'demo-act-1',
    areaId: 'area-admissions',
    type: 'task_updated',
    message: 'Updated "School outreach roadshow – Phase 1"',
    actor: 'Demo',
    createdAt: daysAgo(0),
  },
  {
    id: 'demo-act-2',
    areaId: 'area-special',
    type: 'status_change',
    message: 'Moved "Innovation lab soft launch" to in progress',
    actor: 'Demo',
    createdAt: daysAgo(0),
  },
  {
    id: 'demo-act-3',
    areaId: 'area-recruitment',
    type: 'kpi_updated',
    message: 'Updated KPI "Open Positions Filled" to 12',
    actor: 'Demo',
    createdAt: daysAgo(0),
  },
  {
    id: 'demo-act-4',
    areaId: 'area-qa',
    type: 'task_updated',
    message: 'Flagged "NAAC SSR evidence compilation" as blocked',
    actor: 'Demo',
    createdAt: daysAgo(1),
  },
  {
    id: 'demo-act-5',
    areaId: 'area-strategy',
    type: 'task_created',
    message: 'Created "Finalize FY26 institutional OKRs"',
    actor: 'Demo',
    createdAt: daysAgo(1),
  },
  {
    id: 'demo-act-6',
    areaId: 'area-operational',
    type: 'task_completed',
    message: 'Completed "ERP downtime window communication"',
    actor: 'Demo',
    createdAt: daysAgo(1),
  },
]
